---
- name: Install nova-notify2mail dependencies from Ubuntu repos
  apt:
    name:
      - python3
      - python3-pip
      - python3-requests
      - python3-yaml
      - python3-pika
      - python3-keystoneclient
      - mailutils
    state: present
    update_cache: yes
  become: true

- name: Create application directory
  file:
    path: /opt/nova-notify2mail
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy application script
  copy:
    src: nova_notify2mail.py
    dest: /opt/nova-notify2mail/nova_notify2mail.py
    mode: '0755'

- name: Install systemd unit file
  template:
    src: nova-notify2mail.service.j2
    dest: /etc/systemd/system/nova-notify2mail.service
  notify: restart nova-notify2mail

- name: Ensure systemd drop-in directory exists
  file:
    path: /etc/systemd/system/nova-notify2mail.service.d
    state: directory
    mode: '0755'

- name: Create environment file for nova-notify2mail
  copy:
    dest: /etc/systemd/system/nova-notify2mail.service.d/env.conf
    mode: '0644'
    content: |
      [Service]
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_HOST={{ nova_notify2mail_rabbitmq_host }}"
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_PORT={{ nova_notify2mail_rabbitmq_port }}"
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_USER={{ nova_notify2mail_rabbitmq_user }}"
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_PASS={{ nova_notify2mail_rabbitmq_pass }}"
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_VHOST={{ nova_notify2mail_rabbitmq_vhost }}"
      Environment="NOVA_NOTIFY2MAIL_QUEUE_NAME={{ nova_notify2mail_queue_name }}"
      Environment="NOVA_NOTIFY2MAIL_EXCHANGE={{ nova_notify2mail_exchange }}"
      Environment="NOVA_NOTIFY2MAIL_RABBITMQ_SSL={{ nova_notify2mail_rabbitmq_ssl }}"
      Environment="NOVA_NOTIFY2MAIL_LOG_FILE={{ nova_notify2mail_log_file }}"
      Environment="NOVA_NOTIFY2MAIL_LOG_LEVEL={{ nova_notify2mail_log_level }}"
      Environment="NOVA_NOTIFY2MAIL_OS_AUTH_URL={{ nova_notify2mail_os_auth_url }}"
      Environment="NOVA_NOTIFY2MAIL_OS_USERNAME={{ nova_notify2mail_os_username }}"
      Environment="NOVA_NOTIFY2MAIL_OS_PASSWORD={{ nova_notify2mail_os_password }}"
      Environment="NOVA_NOTIFY2MAIL_OS_PROJECT_NAME={{ nova_notify2mail_os_project_name }}"
      Environment="NOVA_NOTIFY2MAIL_OS_USER_DOMAIN_NAME={{ nova_notify2mail_os_user_domain_name }}"
      Environment="NOVA_NOTIFY2MAIL_OS_PROJECT_DOMAIN_NAME={{ nova_notify2mail_os_project_domain_name }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_SERVER={{ nova_notify2mail_smtp_server }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_PORT={{ nova_notify2mail_smtp_port }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_USERNAME={{ nova_notify2mail_smtp_username }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_PASSWORD={{ nova_notify2mail_smtp_password }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_FROM={{ nova_notify2mail_smtp_from }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_TO={{ nova_notify2mail_smtp_to }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_USE_TLS={{ nova_notify2mail_smtp_use_tls }}"
      Environment="NOVA_NOTIFY2MAIL_SMTP_USE_SSL={{ nova_notify2mail_smtp_use_ssl }}"
  notify: restart nova-notify2mail

- name: Enable nova-notify2mail service
  systemd:
    name: nova-notify2mail
    enabled: yes
    daemon_reload: yes

